GET http://localhost:3003/ping
###

GET http://localhost:3003/bands
###

POST http://localhost:3003/bands
Content-Type: application/json

{
    "id": "b003",
    "name": "coldplay"
}
###

PUT http://localhost:3003/bands/b005
Content-Type: application/json

{
    "newId": "b003",
    "newName": "legiao"
}
###