
GET http://localhost:3003/accounts
###


GET http://localhost:3003/accounts/a003
###

DELETE http://localhost:3003/accounts/a003
###

PUT http://localhost:3003/accounts/a001
Content-Type: application/json
{
   "id": "a003",
    "ownerName": "outroNome",
    "balance": 10,
    "type": "Ouro"
}
###

