POST http://localhost:3001/users/signup
Content-Type: application/json

{
    "name": "Userteste3",
    "email": "userteste3@email.com",
    "password": "12345"
}
###

GET http://localhost:3001/users
###


POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Userteste2",
    "price": 25
}
###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "fulano@email.com",
    "password": "fulano123"
}
###